spring:
  application:
    name: lipari-bank
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

liparibank:
  bank-code: LPBK
  max-transfer-amount: 10000.00
  audit:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: INFO